# Generated by Django 3.0.3 on 2020-02-13 13:58

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=90)),
                ('detailPageName', models.CharField(max_length=90)),
                ('portID', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
                ('typology', django_mysql.models.ListCharField(models.CharField(max_length=90), max_length=90, size=None)),
                ('activityLevel', models.CharField(max_length=90)),
                ('collectionType', models.CharField(max_length=90)),
                ('duration', models.TextField(max_length=100)),
                ('language', django_mysql.models.ListCharField(models.CharField(max_length=90), max_length=90, size=None)),
                ('priceLevel', models.IntegerField()),
                ('currency', models.CharField(max_length=90)),
                ('mealInfo', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('shortDescription', models.CharField(max_length=100)),
                ('longDescription', models.TextField(max_length=300)),
                ('externalContent', models.BooleanField(max_length=90)),
                ('minimumAge', models.CharField(max_length=90)),
                ('wheelChairAccessible', models.BooleanField(max_length=90)),
                ('featured', models.BooleanField(max_length=90)),
            ],
        ),
    ]
